### ISSUE TITLE
Update phoenix_html dependency to be use by Phoenix 1.6.0-rc.0 release

### ISSUE THREAD

**Issue by Francisco-Castro** [miguel-s/ex_fontawesome#3]
It not possible to use this awesome package for projects using the Phoenix 1.6.0-rc.0 release.

**Comment by miguel-s** [comment]
Hi @Francisco-Castro! Thanks for opening the issue.

I'm working on a new release with support for Phoenix 1.6 (branch `phoenix-1.6`).

If you feel adventurous you can start using it by updating you deps to `{:ex_fontawesome, github: "miguel-s/ex_fontawesome", branch: "phoenix-1.6"}`.

**Comment by miguel-s** [comment]
Fixed in v0.3.1
