### ISSUE TITLE
Update to Fontawesome 6.1.1

### ISSUE THREAD

**Issue by eriknaslund** [miguel-s/ex_fontawesome#5]
It'd be great to have an update to Font Awesome 6.1.1.

The reason is that they added [a lot of new icons](https://fontawesome.com/icons/categories/humanitarian) in 6.1.0 as described in their [changelog](https://fontawesome.com/docs/changelog/). I'd love to be able to make use of those.

I'd be happy to make a pull request for it myself, but it's probably just as much work for you to review the PR as doing the whole thing yourself :).

**Comment by miguel-s** [comment]
Hi @eKIK!

Just released version 0.7.1 with FontAwesome 6.1.1

These new icons are amazing 👍

**Comment by eriknaslund** [comment]
@miguel-s, You just made me say "Wow!" out loud at the cafe I'm at, so now people are looking at me like I'm a bit of a weirdo :).
I think this is the quickest issue resolution I've ever seen - nice one!

P.S.
I did a dependency upgrade and can verify that the new icons are working beautifully.
